'use client';
import { primaryButton, secondaryButton } from './styles';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import type { PlannerConfig } from '@/lib/planner/domain';
import { defaultPreferences } from '@/lib/planner/preferences';
import { plannerRequest } from './api';
type Calendar = { id: string; name: string; timezone: string; kind: string; visibility: string; selected: boolean; isPrimary: boolean; lastSyncedAt: string | null };
type Connection = { id: string; email: string; status: string; syncStatus: string; errorCode: string | null; lastSyncAt: string | null; calendars: Calendar[] };
type Settings = { preferences: PlannerConfig; connections: Connection[]; googleConfigured: boolean; googleEnabled: boolean; isAdmin: boolean };
export function PlannerSettings() {
  const [data, setData] = useState<Settings | null>(null), [preferences, setPreferences] = useState<PlannerConfig>(defaultPreferences);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const result = await plannerRequest<Settings>('/settings'); setData(result); setPreferences(result.preferences); } catch (e) { setError(e instanceof Error ? e.message : 'Nastavení se nepodařilo načíst.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const result = new URLSearchParams(window.location.search).get('calendar');
    if (result === 'connected') setNotice('Google účet byl připojen. Spusťte synchronizaci, vyberte kalendáře a synchronizujte jejich události.');
    if (result === 'error') setError('Google účet se nepodařilo připojit. Zkuste připojení znovu a povolte čtení kalendářů.');
  }, []);
  async function action(operation: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setNotice(''); try { await operation(); setNotice(message); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Změnu se nepodařilo uložit.'); } finally { setBusy(false); } }
  function update<K extends keyof PlannerConfig>(key: K, value: PlannerConfig[K]) { setPreferences(p => ({ ...p, [key]: value })); }
  const field = (key: keyof PlannerConfig, label: string) => <label className="block text-sm font-semibold" key={key}>{label}<input type="time" required value={String(preferences[key])} onChange={e => update(key, e.target.value)} className="mt-1 w-full rounded-xl border p-2.5" /></label>;
  const saveCalendar = (calendar: Calendar, patch: Partial<Calendar>) => action(() => plannerRequest(`/calendars/${calendar.id}`, { kind: calendar.kind, visibility: calendar.visibility, selected: calendar.selected, isPrimary: calendar.isPrimary, ...patch }, 'PATCH'), 'Nastavení kalendáře uloženo. Pro načtení událostí spusťte synchronizaci.');
  return <div className="mx-auto max-w-5xl space-y-6"><header><Link href="/planner" className="text-sm font-bold text-emerald-800">← Planner</Link><h1 className="mt-3 text-3xl font-bold">Calendar & Planner</h1><p className="mt-2 text-sm text-slate-500">Váš kalendář a pracovní rytmus v aktuální firmě.</p></header>
    {error && <p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
    {!data ? <p role="status">Načítám nastavení…</p> : <>
      <section className="card space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Moje Google kalendáře</h2><p className="mt-1 max-w-xl text-sm text-slate-600">Připojení patří vám a této firmě. Kolegové standardně vidí pouze obsazenost. Názvy a místa událostí sdílíte až vlastní volbou.</p></div>{data.googleEnabled && data.googleConfigured && <form action="/api/planner/calendar/connect" method="post"><button className={primaryButton}>Připojit Google Calendar</button></form>}</div>
        {!data.googleEnabled && <p className="text-sm text-amber-800">Google Calendar není pro tuto firmu aktivovaný.</p>}{data.googleEnabled && !data.googleConfigured && <p className="text-sm text-amber-800">Připojení Google Calendar ještě není připravené. Obraťte se na správce.</p>}
        {!data.connections.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Zatím nemáte připojený žádný účet.</p>}
        {data.connections.map(connection => <article key={connection.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="break-all font-bold">{connection.email}</h3><p className="mt-1 text-xs text-slate-500">{connection.status === 'REVOKED' ? 'Odpojeno' : connection.status === 'ERROR' ? 'Je potřeba znovu připojit účet' : connection.syncStatus === 'ERROR' ? 'Synchronizace selhala; lze ji zopakovat.' : connection.syncStatus === 'RUNNING' ? 'Synchronizace probíhá' : 'Připojeno'}{connection.lastSyncAt && ` · Aktualizace ${new Date(connection.lastSyncAt).toLocaleString('cs-CZ')}`}</p></div><div className="flex gap-2">{connection.status === 'CONNECTED' && data.googleEnabled && <button disabled={busy} onClick={() => action(async () => { const result = await plannerRequest<{ status: string; errorCode?: string }>(`/connections/${connection.id}/sync`, {}); if (result.status === 'ERROR') throw new Error(result.errorCode === 'REAUTH_REQUIRED' ? 'Google vyžaduje nové připojení.' : 'Synchronizace selhala. Zkuste to později.'); if (result.status !== 'OK') throw new Error('Synchronizace už běží nebo čeká na opakování.'); }, 'Kalendáře aktualizovány.')} className={secondaryButton}>Synchronizovat</button>}{connection.status !== 'REVOKED' && <button disabled={busy} onClick={() => { if (confirm('Odpojit účet a odstranit importované události? Interní bloky a úkoly zůstanou.')) void action(() => plannerRequest(`/connections/${connection.id}`, {}, 'DELETE'), 'Účet byl odpojen.'); }} className={secondaryButton}>Odpojit</button>}</div></div>
          {connection.status === 'CONNECTED' && !connection.calendars.length && <p className="text-sm text-slate-500">Žádné načtené kalendáře. Spusťte synchronizaci a pak vyberte kalendáře k zobrazení.</p>}
          {connection.status === 'CONNECTED' && connection.calendars.map(c => <div key={c.id} className="grid gap-3 rounded-xl bg-slate-50 p-3 sm:grid-cols-2"><div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={c.selected} disabled={busy} onChange={e => saveCalendar(c, { selected: e.target.checked })} />{c.name}</label><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={c.isPrimary} disabled={busy} onChange={e => saveCalendar(c, { isPrimary: e.target.checked })} />Hlavní kalendář</label></div><div className="space-y-2"><label className="block text-xs">Co vidí ostatní<select aria-label={`Viditelnost ${c.name}`} value={c.visibility} disabled={busy} onChange={e => { const visibility = e.target.value; if (visibility === 'FREE_BUSY' || confirm('Povolit kolegům zobrazení názvů a míst událostí v tomto kalendáři?')) void saveCalendar(c, { visibility }); }} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="FREE_BUSY">Pouze volno / obsazeno</option><option value="WORK_DETAILS">Detaily veřejných pracovních událostí</option><option value="FULL">Všechny importované detaily</option></select></label>{data.isAdmin && <label className="block text-xs">Typ kalendáře<select value={c.kind} disabled={busy} onChange={e => saveCalendar(c, { kind: e.target.value })} className="mt-1 w-full rounded-lg border bg-white p-2"><option value="PERSONAL">Osobní</option><option value="COMPANY">Firemní sdílený</option></select></label>}</div></div>)}
        </article>)}
      </section>
      <section className="card"><h2 className="text-xl font-bold">Pracovní rytmus</h2><form className="mt-4 space-y-5" onSubmit={e => { e.preventDefault(); void action(() => plannerRequest('/settings', { preferences }, 'PUT'), 'Preference uloženy.'); }}>
        <label className="block text-sm font-semibold">Časová zóna<input value={preferences.timezone} onChange={e => update('timezone', e.target.value)} required className="mt-1 w-full rounded-xl border p-2.5" placeholder="Europe/Prague" /></label>
        <fieldset><legend className="mb-2 text-sm font-semibold">Pracovní dny</legend><div className="flex flex-wrap gap-3">{['Ne', 'Po', 'Út', 'St', 'Čt', 'Pá', 'So'].map((name, day) => <label key={day} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={preferences.workingDays.includes(day)} onChange={e => update('workingDays', e.target.checked ? [...preferences.workingDays, day] : preferences.workingDays.filter(d => d !== day))} />{name}</label>)}</div></fieldset>
        <div className="grid gap-3 sm:grid-cols-2">{field('workingStart', 'Práce od')}{field('workingEnd', 'Práce do')}{field('lunchStart', 'Oběd od')}{field('lunchEnd', 'Oběd do')}{field('preferredFocusStart', 'Soustředění od')}{field('preferredFocusEnd', 'Soustředění do')}{field('preferredMeetingStart', 'Schůzky od')}{field('preferredMeetingEnd', 'Schůzky do')}<label className="text-sm font-semibold">Rezerva mezi schůzkami (min)<input type="number" min={0} max={120} value={preferences.meetingBufferMinutes} onChange={e => update('meetingBufferMinutes', Number(e.target.value))} className="mt-1 w-full rounded-xl border p-2.5" /></label><label className="text-sm font-semibold">Obvyklá délka schůzky (min)<input type="number" min={15} max={480} value={preferences.defaultMeetingDuration} onChange={e => update('defaultMeetingDuration', Number(e.target.value))} className="mt-1 w-full rounded-xl border p-2.5" /></label></div>
        <fieldset className="space-y-2"><legend className="font-semibold">Časy bez schůzek</legend>{preferences.noMeetingBlocks.map((block, i) => <div key={i} className="flex flex-wrap gap-2"><select aria-label="Den bez schůzek" value={block.day} onChange={e => update('noMeetingBlocks', preferences.noMeetingBlocks.map((b, n) => n === i ? { ...b, day: Number(e.target.value) } : b))} className="rounded-lg border p-2">{['Ne', 'Po', 'Út', 'St', 'Čt', 'Pá', 'So'].map((name, day) => <option key={day} value={day}>{name}</option>)}</select>{(['start', 'end'] as const).map(key => <input key={key} aria-label={key === 'start' ? 'Bez schůzek od' : 'Bez schůzek do'} type="time" value={block[key]} onChange={e => update('noMeetingBlocks', preferences.noMeetingBlocks.map((b, n) => n === i ? { ...b, [key]: e.target.value } : b))} className="min-w-0 rounded-lg border p-2" />)}<button type="button" onClick={() => update('noMeetingBlocks', preferences.noMeetingBlocks.filter((_, n) => n !== i))} className="text-sm text-rose-700">Odebrat</button></div>)}<button type="button" className={secondaryButton} onClick={() => update('noMeetingBlocks', [...preferences.noMeetingBlocks, { day: 5, start: '13:00', end: '17:00' }])}>+ Čas bez schůzek</button></fieldset>
        <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">AI doporučení nejsou v této verzi aktivní. Žádné schůzky se automaticky nepřesouvají.</p>
        <div className="flex flex-wrap gap-2"><button disabled={busy} className={primaryButton}>Uložit moje preference</button>{data.isAdmin && <button type="button" disabled={busy} className={secondaryButton} onClick={() => { if (confirm('Použít tato pravidla jako výchozí pro členy bez vlastních preferencí?')) void action(() => plannerRequest('/settings', { preferences, company: true }, 'PUT'), 'Výchozí firemní pravidla uložena.'); }}>Nastavit jako výchozí pro firmu</button>}</div>
      </form></section>
    </>}
  </div>;
}
