ALTER TYPE "OfferPriceCategory" ADD VALUE IF NOT EXISTS 'PRINT';
ALTER TYPE "OfferPriceCategory" ADD VALUE IF NOT EXISTS 'INSTALLATION';
ALTER TYPE "OfferPriceCategory" ADD VALUE IF NOT EXISTS 'REMOVAL';
