import { academyPrimaryButton, academySecondaryButton } from '@/components/academy/styles';
import Link from 'next/link';
import { BookOpen, Clock, Search } from 'lucide-react';
import { statusLabels, type AcademyStatus } from '@/lib/academy/policy';

export type AcademyCatalogItem = { slug: string; title: string; summary: string; category: string; durationMinutes: number; status: AcademyStatus; version: number };
export function AcademyCatalog({ lessons, query, preview, canManage }: { lessons: AcademyCatalogItem[]; query: string; preview: boolean; canManage: boolean }) {
  const categories = [...new Set(lessons.map(lesson => lesson.category))];
  return <div className="mx-auto max-w-6xl space-y-6 pb-20">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-sm font-semibold text-emerald-700">Návody & Akademie</p><h1 className="text-3xl font-bold tracking-tight">Naučte se další krok</h1><p className="mt-2 text-slate-600">Krátké návody pro práci, kterou právě potřebujete udělat.</p></div>{canManage && <Link className={academySecondaryButton} href="/academy/manage">Správa obsahu a podnětů</Link>}</header>
    {preview && <div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">Redakční náhled. Tyto postupy dosud nemusely být ověřeny v aplikaci. Zaměstnancům se zobrazí až publikované a ověřené lekce.</div>}
    <form action="/academy" method="get" className="card space-y-3"><label htmlFor="academy-query" className="flex items-center gap-2 font-semibold"><Search size={18} aria-hidden="true" />Co potřebujete udělat?</label><div className="flex flex-wrap gap-2"><input id="academy-query" name="q" type="search" defaultValue={query} maxLength={160} placeholder="Například fotografie, GPS nebo navigace" className="min-h-11 min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2" />{preview && <input type="hidden" name="preview" value="1" />}<button type="submit" className={academyPrimaryButton}>Vyhledat</button></div><p className="text-sm text-slate-500">Hledáme v názvech a popisech dostupných lekcí. Zobrazení respektuje vaši aktivní roli a moduly organizace.</p></form>
    {canManage && <div className="flex flex-wrap gap-3 text-sm"><Link href="/academy" aria-current={!preview ? 'page' : undefined} className="underline underline-offset-4">Publikované lekce</Link><Link href="/academy?preview=1" aria-current={preview ? 'page' : undefined} className="underline underline-offset-4">Redakční náhled</Link></div>}
    {!lessons.length ? <section className="card py-10 text-center"><BookOpen className="mx-auto mb-4 text-emerald-700" size={30} aria-hidden="true" /><h2 className="text-xl font-semibold">{query ? 'Nenašli jsme odpovídající návod' : 'Návody pro vás připravujeme'}</h2><p className="mx-auto mt-2 max-w-lg text-slate-600">{query ? 'Zkuste kratší výraz nebo jiný název činnosti.' : 'Jakmile budou postupy ověřené a publikované, objeví se zde. Zatím se můžete obrátit na správce organizace.'}</p>{query && <Link className={academySecondaryButton + ' mt-4'} href={preview ? '/academy?preview=1' : '/academy'}>Zobrazit všechny dostupné lekce</Link>}</section> : categories.map(category => <section key={category} aria-label={category}><h2 className="mb-3 text-xl font-semibold">{category}</h2><div className="grid gap-4 md:grid-cols-2">{lessons.filter(lesson => lesson.category === category).map(lesson => <Link key={lesson.slug} href={`/academy/lessons/${lesson.slug}${preview ? '?preview=1' : ''}`} className="card group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 hover:border-emerald-300"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 text-xs"><span className={lesson.status === 'PUBLISHED' ? 'rounded bg-emerald-50 px-2 py-1 text-emerald-800' : 'rounded bg-amber-50 px-2 py-1 text-amber-900'}>{statusLabels[lesson.status]}</span><span className="flex items-center gap-1 text-slate-500"><Clock size={14} aria-hidden="true" />{lesson.durationMinutes} min</span></div><h3 className="text-lg font-semibold group-hover:text-emerald-700">{lesson.title}</h3><p className="mt-2 text-sm text-slate-600">{lesson.summary}</p><span className="mt-4 inline-block text-sm font-semibold text-emerald-700">Otevřít lekci →</span></Link>)}</div></section>)}
  </div>;
}
