'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Props = { employee: { id:string; firstName:string; lastName:string; email:string|null; phone:string|null; positions:string[]; note:string|null; isActive:boolean } };

export function EmployeeEditForm({ employee }: Props) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/employees/${employee.id}`, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({...data,isActive:data.isActive==='true'}) }); const result = await response.json(); setBusy(false); setMessage(result.error ?? 'Profil byl uložen.'); if (response.ok) router.refresh(); }
  async function remove() { if (!confirm(`Opravdu chcete trvale smazat profil zaměstnance ${employee.firstName} ${employee.lastName}?`)) return; setBusy(true); const res = await fetch(`/api/employees/${employee.id}`, { method: 'DELETE' }); const data = await res.json(); setBusy(false); if (!res.ok) { setMessage(data.error || 'Chyba při mazání.'); } else { router.push('/employees'); } }
  return <details className="card mt-6"><summary className="cursor-pointer text-xl font-bold">Upravit profil zaměstnance</summary><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={submit}><label>Jméno<input className="input mt-1" name="firstName" defaultValue={employee.firstName} required /></label><label>Příjmení<input className="input mt-1" name="lastName" defaultValue={employee.lastName} required /></label><label>E-mail<input className="input mt-1" name="email" type="email" defaultValue={employee.email ?? ''} /></label><label>Telefon<input className="input mt-1" name="phone" defaultValue={employee.phone ?? ''} /></label><label className="md:col-span-2">Pracovní pozice<input className="input mt-1" name="positions" defaultValue={employee.positions.join(', ')} placeholder="Technik, obchodník, montážník" /><span className="mt-1 block text-xs text-slate-500">Více pozic oddělte čárkou.</span></label><label>Pracovní stav<select className="input mt-1" name="isActive" defaultValue={String(employee.isActive)}><option value="true">Aktivní</option><option value="false">Neaktivní</option></select></label><label className="md:col-span-2">Poznámka<textarea className="input mt-1" name="note" defaultValue={employee.note ?? ''} /></label><div className="md:col-span-2 flex items-center justify-between gap-3 pt-2"><button className="rounded-xl bg-slate-950 px-4 py-2 text-white disabled:opacity-50" disabled={busy}>{busy ? 'Ukládám…' : 'Uložit profil'}</button><button type="button" onClick={remove} className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 text-xs font-bold text-rose-700 hover:bg-rose-100 disabled:opacity-50 transition" disabled={busy}>🗑️ Smazat profil trvale</button></div>{message && <p className="text-sm md:col-span-2" role="status">{message}</p>}</form></details>;
}
