'use client';
import { GoogleMap, MarkerF, useJsApiLoader } from '@react-google-maps/api';
import { useMemo, useState } from 'react';
import type { Carrier } from '@/lib/types';
import { carrierMapColor } from '@/lib/mock-data';
import { CarrierDetail } from './CarrierDetail';
import { CarrierForm } from './CarrierForm';
export function MapView({ initialCarriers }: { initialCarriers: Carrier[] }) { const [items,setItems]=useState(initialCarriers); const [selected,setSelected]=useState<Carrier|undefined>(items[0]); const [draft,setDraft]=useState<Partial<Carrier>|undefined>(); const { isLoaded }=useJsApiLoader({ googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ?? '' }); const center=useMemo(()=>({lat:50.0755,lng:14.4378}),[]); if(!process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY) return <FallbackMap items={items} setSelected={setSelected} setDraft={setDraft}/>; return <div className="grid lg:grid-cols-[1fr_420px] gap-4"><div className="h-[calc(100vh-8rem)] overflow-hidden rounded-2xl border bg-slate-100">{isLoaded&&<GoogleMap mapContainerStyle={{width:'100%',height:'100%'}} center={center} zoom={8} onClick={e=>setDraft({latitude:e.latLng?.lat(),longitude:e.latLng?.lng(), city:'', status:'ACTIVE', type:'BILLBOARD'})}>{items.map(c=><MarkerF key={c.id} position={{lat:c.latitude,lng:c.longitude}} onClick={()=>setSelected(c)} icon={{path:google.maps.SymbolPath.CIRCLE,scale:9,fillColor:carrierMapColor(c),fillOpacity:1,strokeWeight:2,strokeColor:'#fff'}} />)}</GoogleMap>}</div><aside className="card max-h-[calc(100vh-8rem)] overflow-auto">{draft?<><h2 className="text-xl font-bold mb-4">Nový nosič</h2><CarrierForm carrier={draft} onSaved={c=>{setItems([...items,c]);setDraft(undefined);setSelected(c)}}/></>:selected?<CarrierDetail carrier={selected}/>:null}</aside></div> }
function FallbackMap({items,setSelected,setDraft}:{items:Carrier[];setSelected:(c:Carrier)=>void;setDraft:(c:Partial<Carrier>)=>void}){const [active,setActive]=useState(items[0]); return <div className="grid lg:grid-cols-[1fr_420px] gap-4"><button className="relative h-[calc(100vh-8rem)] rounded-2xl border bg-gradient-to-br from-emerald-50 to-sky-100" onClick={()=>setDraft({latitude:50.0755,longitude:14.4378,city:'Praha',status:'ACTIVE',type:'BILLBOARD'})}>{items.map((c,i)=><span key={c.id} onClick={(e)=>{e.stopPropagation();setActive(c);setSelected(c)}} className="absolute rounded-full border-2 border-white px-3 py-2 text-xs text-white shadow" style={{left:`${20+i*22}%`,top:`${30+i*14}%`,background:carrierMapColor(c)}}>{c.code}</span>)}<span className="absolute bottom-4 left-4 text-sm text-slate-600">Nastavte NEXT_PUBLIC_GOOGLE_MAPS_API_KEY pro Google Maps. Kliknutím do mock mapy přidáte bod.</span></button><aside className="card"><CarrierDetail carrier={active}/></aside></div>}
