'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { CrewInput, PlanningInput, PlanningProfile, PlanView } from '@/lib/field-planning/contracts';
import { RouteMap } from './field-planning/RouteMap';
import { PlanningProfileForm } from './field-planning/PlanningProfileForm';
import { JobPlanningSettings } from './field-planning/JobPlanningSettings';
type Loaded = { profile: PlanningProfile | null; data: PlanningInput | null; plans: PlanView[] };
function mapsLinks(plan: PlanView, crewId: string) {
  const crew = plan.result.crews.find(c => c.id === crewId); if (!crew) return [];
  const coords = (p: { latitude: number; longitude: number }) => `${p.latitude},${p.longitude}`;
  const points = [crew.startLocation ?? plan.profile.depot, ...crew.stops.map(s => s.location), plan.profile.endLocation]; const links: string[] = [];
  for (let i = 0; i < points.length - 1; i += 4) {
    const slice = points.slice(i, i + 5);
    links.push(`https://www.google.com/maps/dir/?${new URLSearchParams({ api: '1', origin: coords(slice[0]), destination: coords(slice.at(-1)!), waypoints: slice.slice(1, -1).map(coords).join('|'), travelmode: 'driving' })}`);
  } return links;
}
export function WorkRoutePlanner({ defaultDate, country, navigation = false }: { navigation?: boolean; defaultDate: string; country: string | null }) {
  const [date, setDate] = useState(defaultDate); const [startTime, setStartTime] = useState(''); const [loaded, setLoaded] = useState<Loaded | null>(null);
  const [plan, setPlan] = useState<PlanView | null>(null); const [crews, setCrews] = useState<CrewInput[]>([]);
  const [selectedJobs, setSelectedJobs] = useState<string[]>([]); const [active, setActive] = useState('');
  const [sourceFilter, setSourceFilter] = useState('all'); const [query, setQuery] = useState(''); const [readyOnly, setReadyOnly] = useState(false);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [settings, setSettings] = useState(false);
  const [inputsChanged, setInputsChanged] = useState(false); const [acceptEstimated, setAcceptEstimated] = useState(false); const requestKey = useRef<string | null>(null); const loadCounter = useRef(0);
  const load = useCallback(async () => {
    const ticket = ++loadCounter.current; setError('');
    try {
      const response = await fetch(`/api/work/route?date=${date}`); const data = await response.json(); if (!response.ok) throw new Error(data.error);
      if (ticket !== loadCounter.current) return; setInputsChanged(false); setLoaded(data); setPlan(data.plans[0] ?? null); setCrews(data.data?.crews ?? []);
      setSelectedJobs(data.data?.jobs.filter((j: { status: string }) => !['DONE', 'CANCELLED'].includes(j.status)).map((j: { id: string }) => j.id) ?? []);
      setActive(data.plans[0]?.result.crews[0]?.id ?? '');
    } catch (e) { setError(e instanceof Error ? e.message : 'Načtení selhalo.'); }
  }, [date]);
  useEffect(() => { setPlan(null); setLoaded(null); requestKey.current = null; void load(); }, [load]);
  async function action(kind: 'generate' | 'replan' | 'approve' | 'cancel') {
    setBusy(true); setError('');
    try {
      const generating = kind === 'generate' || kind === 'replan'; requestKey.current ??= crypto.randomUUID();
      const response = await fetch('/api/work/route', { method: generating ? 'POST' : 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(generating ? { date, startTime: startTime || undefined, requestKey: requestKey.current, crews, jobIds: selectedJobs, ...(kind === 'replan' ? { parentPlanId: plan?.id } : {}) } : { action: kind, id: plan?.id, acceptEstimated }) });
      const value = await response.json(); if (!response.ok) throw new Error(value.error);
      setInputsChanged(false); setPlan(value); setActive(value.result.crews[0]?.id ?? ''); requestKey.current = null; setAcceptEstimated(false);
      setLoaded(old => old ? { ...old, plans: [value, ...old.plans.filter(p => p.id !== value.id)] } : old);
    } catch (e) { setError(e instanceof Error ? e.message : 'Operace selhala.'); } finally { setBusy(false); }
  }
  function updateCrews(value: CrewInput[]) { setCrews(value); setInputsChanged(true); requestKey.current = null; }
  const time = (v: string) => new Date(v).toLocaleTimeString('cs-CZ', { timeZone: plan?.profile.timezone ?? loaded?.profile?.timezone ?? 'Europe/Prague', hour: '2-digit', minute: '2-digit' });
  const visibleJobs = loaded?.data?.jobs.filter(j => (sourceFilter === 'all' || Boolean(j.navigationPointId) === (sourceFilter === 'navigation')) && (!readyOnly || !j.blockedReason) && [j.title, j.clientName, j.orderNumber, j.address].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())) ?? [];
  const crew = plan?.result.crews.find(c => c.id === active);
  return <div className="mx-auto max-w-[1600px] space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Práce / Terénní operace</p><h1 className="mt-1 text-3xl font-bold">AI Route & Field Planner</h1><p className="mt-2 text-slate-600">Kdo, čím a kdy. Návrh se stane provozním plánem až po vašem schválení.</p></div><div className="flex gap-4 text-sm font-semibold text-sky-700"><Link href="/work">Plán práce</Link><Link href="/my-route">Moje trasa</Link><button onClick={() => setSettings(!settings)}>Nastavení organizace</button></div></header>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}
    {(settings || (loaded && !loaded!.profile)) && <PlanningProfileForm navigation={navigation} country={country} initial={loaded?.profile ?? null} onSaved={() => { setSettings(false); void load(); }} />}
    <section className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4"><label className="text-sm font-semibold">Den<input className="input" type="date" value={date} disabled={busy} onChange={e => setDate(e.target.value)} /></label>
      <label className="text-sm font-semibold">Nejdřívější odjezd ({loaded?.profile?.timezone})<input className="input" type="time" value={startTime} disabled={busy} onChange={e => { setStartTime(e.target.value); setInputsChanged(true); requestKey.current = null; }} /></label><button className="rounded-xl bg-sky-700 px-4 py-3 font-semibold text-white disabled:opacity-40" disabled={busy || !loaded?.data || !selectedJobs.length || !crews.length} onClick={() => void action('generate')}>{busy ? 'Zpracovávám…' : 'Vygenerovat plán'}</button>
      <button className="rounded-xl border px-4 py-3 disabled:opacity-40" disabled={busy || !plan || !['DRAFT', 'APPROVED', 'ACTIVE'].includes(plan.status)} onClick={() => void action('replan')}>Přepočítat zbývající plán</button>
      <button className="rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white disabled:opacity-40" disabled={busy || inputsChanged || plan?.status !== 'DRAFT' || Boolean(plan.result.conflicts.length || plan.result.unassigned.length)} onClick={() => void action('approve')}>Schválit plán</button>
      <button className="px-3 py-2 text-sm text-slate-500 disabled:opacity-40" disabled={busy || plan?.status !== 'DRAFT'} onClick={() => void action('cancel')}>Zrušit návrh</button>
      {!!loaded?.plans.length && <label className="ml-auto text-sm">Verze<select className="input" value={plan?.id ?? ''} onChange={e => { const chosen = loaded.plans.find(p => p.id === e.target.value)!; setPlan(chosen); setActive(chosen.result.crews[0]?.id ?? ''); }}><option value="" disabled>Vyberte</option>{loaded.plans.map(p => <option key={p.id} value={p.id}>v{p.version} · {p.status}</option>)}</select></label>}
    </section>
    {inputsChanged && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Výběr se změnil. Před schválením vygenerujte nebo přepočítejte návrh.</p>}{plan && <section className="rounded-2xl bg-slate-900 p-5 text-white"><div className="flex flex-wrap gap-6"><strong>v{plan.version} · {plan.status}</strong><span>{plan.result.crews.reduce((n, c) => n + c.stops.length, 0)} zastávek / {new Set(plan.result.crews.flatMap(c => c.stops.map(s => s.workOrderId || s.navigationOrderId))).size} zakázek / {plan.result.crews.length} posádek</span><span>{(plan.result.distanceMeters / 1000).toFixed(1)} km</span><span>Jízda {Math.round(plan.result.travelSeconds / 60)} min</span><span>Práce {plan.result.serviceMinutes} min</span></div><p className="mt-3 text-sm text-slate-300">{plan.result.explanation}</p>{plan.result.estimated && plan.status === 'DRAFT' && <label className="mt-3 flex gap-2 text-sm text-amber-200"><input type="checkbox" checked={acceptEstimated} onChange={e => setAcceptEstimated(e.target.checked)} />Ověřil/a jsem odhadované přejezdy a souhlasím s jejich použitím.</label>}</section>}
    <div className="grid items-start gap-4 xl:grid-cols-[290px_minmax(300px,1fr)_340px]">
      <aside className="space-y-4"><section className="card"><h2 className="font-bold">Úkoly k naplánování</h2><p className="mb-3 text-xs text-slate-500">Včetně nedokončených starších úkolů.</p><label className="block text-xs">Typ zastávky<select className="input" value={sourceFilter} onChange={e => setSourceFilter(e.target.value)}><option value="all">Všechny</option><option value="work">Běžná práce</option>{navigation && <option value="navigation">Navigation</option>}</select></label><label className="mt-2 block text-xs">Klient, zakázka, město nebo adresa<input className="input" value={query} onChange={e => setQuery(e.target.value)} /></label><label className="my-2 flex gap-2 text-xs"><input type="checkbox" checked={readyOnly} onChange={e => setReadyOnly(e.target.checked)} />Pouze neplánované a připravené</label><p className="my-2 text-xs">Vybráno {selectedJobs.length} zastávek · zobrazeno {visibleJobs.length}</p><div className="mb-3 flex flex-wrap gap-3 text-xs"><button className="font-semibold text-sky-700" onClick={() => { setSelectedJobs(visibleJobs.map(j => j.id)); setInputsChanged(true); requestKey.current = null; }}>Vybrat pouze zobrazené</button><button className="text-slate-600" onClick={() => { setSelectedJobs([]); setInputsChanged(true); requestKey.current = null; }}>Zrušit výběr</button></div><div className="max-h-80 space-y-3 overflow-auto">{visibleJobs.map(j => <div key={j.id}><label className="flex gap-2 text-sm"><input type="checkbox" checked={selectedJobs.includes(j.id)} onChange={e => { setSelectedJobs(old => e.target.checked ? [...old, j.id] : old.filter(id => id !== j.id)); setInputsChanged(true); requestKey.current = null; }} /><span><Link className="font-semibold hover:underline" href={j.navigationOrderId ? `/navigation/orders/${j.navigationOrderId}` : `/work/${j.parentWorkOrderId ?? j.id}`}>{j.title}</Link><small className="block text-slate-500">{j.clientName} · {j.orderNumber} · {j.priority} · {j.serviceMinutes ?? loaded!.profile?.serviceMinutes[j.workType] ?? '?'} min</small><small className="block text-slate-500">{j.address} · {j.location ? `${j.location.latitude}, ${j.location.longitude}` : 'Chybí GPS'}</small>{j.blockedReason && <small className="block text-amber-700">{j.blockedReason}</small>}{j.deadlineAt && <small className="block text-amber-700">Termín {new Date(j.deadlineAt).toLocaleString('cs-CZ', { timeZone: loaded!.profile!.timezone })}</small>}</span></label><JobPlanningSettings job={j} onSaved={load} employees={loaded!.data!.employees} jobs={loaded!.data!.jobs} timezone={loaded!.profile!.timezone} /></div>)}</div></section>
        <section className="card space-y-3"><h2 className="font-bold">Posádky a dostupnost</h2>{loaded?.data?.employees.filter(e => e.isActive).map(e => <p key={e.id} className={`text-xs ${e.available ? 'text-emerald-700' : 'text-red-700'}`}>{e.name} · {e.available ? 'dostupný' : 'absence / jiná práce'} · {e.positions.join(', ')}</p>)}
          {crews.map((c, index) => <div key={c.id} className="space-y-2 rounded-xl border p-3"><div className="flex justify-between text-sm font-bold"><span>Posádka {index + 1}</span><button aria-label="Odebrat posádku" onClick={() => updateCrews(crews.filter(x => x.id !== c.id))}>×</button></div><label className="block text-xs">Pracovníci<select multiple className="input mt-1 min-h-20" value={c.employeeIds} onChange={e => updateCrews(crews.map(x => x.id === c.id ? { ...x, employeeIds: Array.from(e.target.selectedOptions, o => o.value) } : x))}>{loaded?.data?.employees.filter(e => e.isActive).map(e => <option key={e.id} value={e.id}>{e.name}{!e.available ? ' (nedostupný)' : ''}</option>)}</select></label><label className="block text-xs">Vozidlo<select className="input mt-1" value={c.vehicleId ?? ''} onChange={e => updateCrews(crews.map(x => x.id === c.id ? { ...x, vehicleId: e.target.value || null } : x))}><option value="">Bez vozidla</option>{loaded?.data?.vehicles.map(v => <option key={v.id} value={v.id}>{v.name} · {v.status}{v.reserved ? ' / rezervace' : ''}</option>)}</select></label><label className="block text-xs">Aktuální GPS při přepočtu (lat, lng)<input className="input mt-1" placeholder="Potvrďte skutečnou polohu" onBlur={e => { const values = e.target.value.split(',').map(Number); if (values.length === 2 && values.every(Number.isFinite)) updateCrews(crews.map(x => x.id === c.id ? { ...x, startLocation: { latitude: values[0], longitude: values[1] } } : x)); }} /></label></div>)}
          <button className="text-sm font-semibold text-sky-700" onClick={() => updateCrews([...crews, { id: crypto.randomUUID(), employeeIds: [], vehicleId: null }])}>+ Přidat posádku</button>{plan && ['APPROVED', 'ACTIVE'].includes(plan.status) && <button className="block text-sm text-sky-700" onClick={() => updateCrews(plan.result.crews.map(c => ({ id: c.id, employeeIds: c.employeeIds, vehicleId: c.vehicleId })))}>Použít posádky schváleného plánu</button>}
        </section></aside>
      <main className="space-y-3"><div className="flex flex-wrap gap-2">{plan?.result.crews.map((c, i) => <button key={c.id} onClick={() => setActive(c.id)} className={`rounded-full px-4 py-2 text-sm font-semibold ${active === c.id ? 'bg-sky-700 text-white' : 'bg-white'}`}>Posádka {i + 1} · {c.stops.length}</button>)}</div><RouteMap result={plan?.result} depot={loaded?.profile?.depot} active={active} /><p className="text-xs text-slate-500">Přerušovaná čára = odhad. Plná čára = silniční trasa.</p>{plan && [...plan.result.conflicts, ...plan.result.unassigned].map((a, i) => <p key={i} className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{a.code}: {a.message}</p>)}</main>
      <aside className="space-y-3">{crew ? <><section className="card"><h2 className="text-xl font-bold">{crew.names.join(' + ')}</h2><p className="text-sm text-slate-500">{crew.vehicleName ?? 'Bez vozidla'}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p>Odjezd <strong>{time(crew.departureAt)}</strong></p><p>Návrat <strong>{time(crew.endAt)}</strong></p><p>{(crew.distanceMeters / 1000).toFixed(1)} km</p><p>{Math.round(crew.travelSeconds / 60)} min jízdy</p><p>{crew.serviceMinutes} min práce</p><p>{crew.breakMinutes} min přestávka před návratem</p></div>{mapsLinks(plan!, active).map((href, i, links) => <a key={href} href={href} target="_blank" rel="noreferrer" className="mt-3 block text-sm font-semibold text-sky-700">Google Maps{links.length > 1 ? ` · část ${i + 1}/${links.length}` : ''} ↗</a>)}</section><ol className="space-y-3">{crew.stops.map(s => <li key={s.jobId ?? s.workOrderId} className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold text-sky-700">{s.routeOrder}. · ETA {time(s.arrivalAt)} · práce {time(s.startAt)}–{time(s.endAt)}</p><Link href={s.navigationOrderId ? `/navigation/orders/${s.navigationOrderId}` : `/work/${s.workOrderId}`} className="mt-1 block font-bold">{s.title}</Link><p className="mt-2 text-xs text-slate-500">{s.reason}</p></li>)}</ol></> : <section className="card text-sm text-slate-500">Vyberte úkoly, pracovníky a vozidla. Návrh zobrazí pořadí a časy.</section>}</aside>
    </div></div>;
}
