ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'PROMO_BENCH';
ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'PROMO_HORIZON';
ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'CITY_POSTER';
ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'NAVIGATION';
ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'PROMO_TOWER';
ALTER TYPE "CarrierType" ADD VALUE IF NOT EXISTS 'PROMO_MINITOWER';

ALTER TYPE "MediaType" ADD VALUE IF NOT EXISTS 'PROMO_BENCH';
ALTER TYPE "MediaType" ADD VALUE IF NOT EXISTS 'PROMO_HORIZON';
ALTER TYPE "MediaType" ADD VALUE IF NOT EXISTS 'CITY_POSTER';
ALTER TYPE "MediaType" ADD VALUE IF NOT EXISTS 'PROMO_TOWER';
ALTER TYPE "MediaType" ADD VALUE IF NOT EXISTS 'PROMO_MINITOWER';
