'use client';

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { Archive, Pencil, Plus } from 'lucide-react';
import type { OfferPriceRuleOption } from '@/lib/offers/view-model';

type Rule = OfferPriceRuleOption & { active: boolean; sortOrder: number };
const emptyRule = { id: '', code: '', category: 'RENTAL', label: '', description: '', mediaType: '', pricingSegment: 'COMMERCIAL', city: '', validFrom: '', validTo: '', minDurationMonths: '', maxDurationMonths: '', calculation: 'PER_SURFACE', unit: 'měsíc', unitPrice: '', defaultSelected: false, active: true, sortOrder: 0 } as const;
const categoryLabels = { RENTAL: 'Pronájem', PRINT: 'Tisk', INSTALLATION: 'Montáž', REMOVAL: 'Demontáž', PRODUCTION: 'Výroba', SERVICE: 'Služba' } as const;
const segmentLabels = { COMMERCIAL: 'Komerční', CULTURE_SPORT: 'Kultura / Sport', PUBLIC_NONPROFIT: 'Veřejný / neziskový', CUSTOM: 'Individuální' } as const;
const mediaTypes = ['NAVIGATION_SIGN', 'BILLBOARD', 'BIGBOARD', 'CITYLIGHT', 'BANNER', 'FACADE', 'LED_SCREEN', 'PROMO_BENCH', 'PROMO_HORIZON', 'CITY_POSTER', 'PROMO_TOWER', 'PROMO_MINITOWER', 'OTHER'];

export function OfferPriceCatalogSettings() {
  const [rules, setRules] = useState<Rule[]>([]); const [form, setForm] = useState<Record<string, string | number | boolean>>({ ...emptyRule });
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const [mediaFilter, setMediaFilter] = useState(''); const [segmentFilter, setSegmentFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [validOnly, setValidOnly] = useState(false);
  const load = useCallback(async () => { setLoading(true); const response = await fetch('/api/offer-price-rules'); const data = await response.json(); if (response.ok) setRules(data); else setMessage(data.error ?? 'Ceník se nepodařilo načíst.'); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const today = new Date().toISOString().slice(0, 10); return rules.filter((rule) => (!mediaFilter || rule.mediaType === mediaFilter) && (!segmentFilter || rule.pricingSegment === segmentFilter) && (!categoryFilter || rule.category === categoryFilter) && (!validOnly || ((!rule.validFrom || rule.validFrom <= today) && (!rule.validTo || rule.validTo >= today)))); }, [rules, mediaFilter, segmentFilter, categoryFilter, validOnly]);
  async function save(event: FormEvent) { event.preventDefault(); setMessage(''); const id = String(form.id || ''); const response = await fetch(id ? `/api/offer-price-rules/${id}` : '/api/offer-price-rules', { method: id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? 'Sazbu se nepodařilo uložit.'); setForm({ ...emptyRule }); setMessage('Sazba byla uložena. Historické nabídky zůstávají beze změny.'); await load(); }
  function edit(rule: Rule) { setForm({ ...rule, description: rule.description ?? '', mediaType: rule.mediaType ?? '', city: rule.city ?? '', validFrom: rule.validFrom ?? '', validTo: rule.validTo ?? '', minDurationMonths: rule.minDurationMonths ?? '', maxDurationMonths: rule.maxDurationMonths ?? '' }); document.getElementById('offer-price-form')?.scrollIntoView({ behavior: 'smooth' }); }
  async function archive(rule: Rule) { const response = await fetch(`/api/offer-price-rules/${rule.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...rule, active: false }) }); if (response.ok) await load(); }
  return <section className="mt-8 space-y-5"><div><h2 className="text-2xl font-semibold">Ceník nabídek</h2><p className="text-sm text-slate-500">Sazby podle média, segmentu, kategorie, lokality a platnosti. AI nikdy nedoplňuje chybějící cenu.</p></div>{message && <p className="rounded-xl bg-sky-50 p-3 text-sm text-sky-800">{message}</p>}
    <form className="card grid gap-4 md:grid-cols-2 xl:grid-cols-4" id="offer-price-form" onSubmit={save}><h3 className="flex items-center gap-2 text-lg font-semibold md:col-span-2 xl:col-span-4"><Plus size={18} />{form.id ? 'Upravit sazbu' : 'Přidat sazbu'}</h3>
      <Field label="Cenový segment"><select className="input" value={String(form.pricingSegment)} onChange={(e) => setForm((v) => ({ ...v, pricingSegment: e.target.value }))}>{Object.entries(segmentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
      <Field label="Kategorie"><select className="input" value={String(form.category)} onChange={(e) => setForm((v) => ({ ...v, category: e.target.value }))}>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
      <Field label="Typ média"><select className="input" value={String(form.mediaType)} onChange={(e) => setForm((v) => ({ ...v, mediaType: e.target.value }))}><option value="">Všechna média</option>{mediaTypes.map((value) => <option key={value}>{value}</option>)}</select></Field>
      <Field label="Město (volitelné)"><input className="input" value={String(form.city)} onChange={(e) => setForm((v) => ({ ...v, city: e.target.value }))} /></Field>
      <Field label="Název"><input className="input" required value={String(form.label)} onChange={(e) => setForm((v) => ({ ...v, label: e.target.value }))} /></Field><Field label="Interní kód"><input className="input" required value={String(form.code)} onChange={(e) => setForm((v) => ({ ...v, code: e.target.value }))} /></Field>
      <Field label="Cena bez DPH"><input className="input" min="0" required step="0.01" type="number" value={String(form.unitPrice)} onChange={(e) => setForm((v) => ({ ...v, unitPrice: e.target.value }))} /></Field><Field label="Jednotka"><input className="input" required value={String(form.unit)} onChange={(e) => setForm((v) => ({ ...v, unit: e.target.value }))} /></Field>
      <Field label="Platnost od"><input className="input" type="date" value={String(form.validFrom)} onChange={(e) => setForm((v) => ({ ...v, validFrom: e.target.value }))} /></Field><Field label="Platnost do"><input className="input" type="date" value={String(form.validTo)} onChange={(e) => setForm((v) => ({ ...v, validTo: e.target.value }))} /></Field>
      <Field label="Min. délka měsíců"><input className="input" min="1" type="number" value={String(form.minDurationMonths)} onChange={(e) => setForm((v) => ({ ...v, minDurationMonths: e.target.value }))} /></Field><Field label="Max. délka měsíců"><input className="input" min="1" type="number" value={String(form.maxDurationMonths)} onChange={(e) => setForm((v) => ({ ...v, maxDurationMonths: e.target.value }))} /></Field>
      <input type="hidden" value={String(form.calculation)} /><div className="flex justify-end gap-2 md:col-span-2 xl:col-span-4">{form.id && <button className="rounded-xl border px-4 py-2" onClick={() => setForm({ ...emptyRule })} type="button">Zrušit</button>}<button className="btn-primary" type="submit">Uložit sazbu</button></div>
    </form>
    <div className="card flex flex-wrap gap-3"><select className="input max-w-52" value={mediaFilter} onChange={(e) => setMediaFilter(e.target.value)}><option value="">Všechna média</option>{mediaTypes.map((value) => <option key={value}>{value}</option>)}</select><select className="input max-w-52" value={segmentFilter} onChange={(e) => setSegmentFilter(e.target.value)}><option value="">Všechny segmenty</option>{Object.entries(segmentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="input max-w-52" value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}><option value="">Všechny kategorie</option>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label className="flex items-center gap-2 text-sm"><input checked={validOnly} onChange={(e) => setValidOnly(e.target.checked)} type="checkbox" />Platné dnes</label></div>
    <div className="card overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-3">Položka</th><th>Segment</th><th>Kategorie</th><th>Médium / město</th><th>Platnost</th><th className="text-right">Cena</th><th /></tr></thead><tbody>{visible.map((rule) => <tr className={`border-b ${rule.active ? '' : 'opacity-45'}`} key={rule.id}><td className="py-3"><strong>{rule.label}</strong><div className="text-xs text-slate-400">{rule.code}</div></td><td>{segmentLabels[rule.pricingSegment]}</td><td>{categoryLabels[rule.category]}</td><td>{rule.mediaType ?? 'Všechna'}{rule.city ? ` · ${rule.city}` : ''}</td><td>{rule.validFrom ?? 'bez omezení'} – {rule.validTo ?? 'bez omezení'}</td><td className="text-right font-semibold">{Number(rule.unitPrice).toLocaleString('cs-CZ')} Kč / {rule.unit}</td><td className="space-x-2 text-right"><button className="rounded-lg border p-2" onClick={() => edit(rule)} type="button"><Pencil size={14} /></button>{rule.active && <button className="rounded-lg border p-2" onClick={() => void archive(rule)} type="button"><Archive size={14} /></button>}</td></tr>)}</tbody></table>{loading && <p className="py-5 text-sm">Načítám ceník…</p>}</div>
  </section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-medium"><span className="mb-1 block">{label}</span>{children}</label>; }
