'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export function OfferActions({ offerId, status, converted, canConvert }: { offerId: string; status: string; converted: boolean; canConvert: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [publicUrl, setPublicUrl] = useState('');
  async function action(name: string, body?: unknown) { setBusy(name); setMessage(''); try { const response = await fetch(`/api/offers/${offerId}/${name}`, { method: 'POST', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json() as { error?: string; path?: string; offer?: { id?: string } }; if (!response.ok) throw new Error(data.error || 'Akci se nepodařilo dokončit.'); if (data.path) setPublicUrl(`${window.location.origin}${data.path}`); if (name === 'duplicate' && data.offer?.id) router.push(`/offers/${data.offer.id}`); else router.refresh(); setMessage('Akce byla úspěšně dokončena.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Akce selhala.'); } finally { setBusy(''); } }
  return <div className="space-y-3"><div className="flex flex-wrap gap-2">{status === 'DRAFT' && <><a className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" href={`/offers/${offerId}/edit`}>Upravit</a><button className="btn-primary" disabled={Boolean(busy)} onClick={() => void action('send')}>Odeslat</button></>}{status === 'SENT' && <>{canConvert && <button className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white" disabled={Boolean(busy)} onClick={() => void action('accept')}>Přijmout interně</button>}<button className="rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white" disabled={Boolean(busy)} onClick={() => void action('reject')}>Zamítnout</button></>}{(status === 'DRAFT' || status === 'SENT') && <button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" disabled={Boolean(busy)} onClick={() => void action('expire')}>Expirovat</button>}<button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" disabled={Boolean(busy)} onClick={() => void action('duplicate')}>Duplikovat</button><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" disabled={Boolean(busy)} onClick={() => void action('publish')}>Vytvořit / obnovit veřejný odkaz</button>{status === 'ACCEPTED' && canConvert && <><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" disabled={Boolean(busy) || converted} onClick={() => void action('convert-to-occupancy', { targetStatus: 'OCCUPIED' })}>{converted ? 'Již převedeno' : 'Převést na obsazenost'}</button><button className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold" disabled={Boolean(busy) || converted} onClick={() => void action('convert-to-occupancy', { targetStatus: 'RESERVED' })}>Převést na rezervaci</button></>}</div>{publicUrl && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><b>Nový veřejný odkaz (zobrazí se pouze nyní):</b><div className="mt-2 flex gap-2"><input className="input" readOnly value={publicUrl} /><button className="rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white" onClick={() => navigator.clipboard.writeText(publicUrl)}>Kopírovat</button></div></div>}{message && <p className="text-sm text-slate-600" aria-live="polite">{message}</p>}</div>;
}
