import { PrismaClient, VehicleType, VehicleStatus } from '@prisma/client';
import { getTenantContext, enterTenantContext } from '../lib/tenant-context';
import { tenantPrismaExtension } from '../lib/tenant-prisma';

const databaseUrl = process.env.DATABASE_URL ?? process.env.POSTGRES_PRISMA_URL ?? process.env.POSTGRES_URL;
if (!getTenantContext()) enterTenantContext({ organizationId: process.env.ORGANIZATION_ID ?? 'org_seepoint_default', source: 'script' });
const prisma = new PrismaClient(databaseUrl ? { datasourceUrl: databaseUrl } : undefined).$extends(tenantPrismaExtension) as unknown as PrismaClient;

const vehiclesData = [
  // VOZÍKY
  {
    name: 'VOZIK 1 (1 billboardový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '8T0 9318',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-03-10'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    repairNotes: 'nesvítí pravé světlo, nesvítí levá strana',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1T7MTS_GWZ6r57G0mGIHXB01ms7tzOjhO/view',
    vin: 'SUCW3F30FC2003923',
  },
  {
    name: 'VOZIK 2 (2 billboardový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '1TJ 2528',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-03-22'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    repairNotes: 'nesvítí pravá brzda a blinkr',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1Hki_hyfqfRRJEHO7NL69Ev2Fe7gCqVrn/view',
    vin: 'SUCW3F30FC2003924',
  },
  {
    name: 'VOZIK 3 (3 billboardový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '7T4 4393',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2030-05-19'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1nScQnPU6wNM7aVTBz4Xp2xySTe0c7gkb/view',
    vin: 'SUCW3F30FC2003925',
  },
  {
    name: 'VOZIK 4 (1 nápravový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '7T4 4013',
    status: 'SERVICE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-03-01'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    repairNotes: 'opravit celý po havárii',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1emnCoNFfiTQbatZGfsNBQXwi7nfuIRBT/view',
    vin: 'SUCO75D0FB0015866',
  },
  {
    name: 'VOZIK 5 (2 nápravový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '7T4 4352',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-03-14'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    repairNotes: '2.7. komplet opraveno',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1tIcEMc74EF9cNHu00W6K1qlu5XSXJbyv/view',
    vin: 'SUCW3F30FC2003733',
  },
  {
    name: 'VOZIK 6 (2 nápravový PLACHTA)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '2TH 1686',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2028-06-27'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    repairNotes: 'je prasklá plachta',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1u1M361eaK7ruTmL_0NT8eHomsOOKJXKT/view',
    vin: 'SUCE2ASA4N1004726',
  },
  {
    name: 'VOZIK 7 (2 nápravový)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '2TH 2232',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2029-03-02'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Karel kontrola',
    tiresInfo: '155/80 R13 84N',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1Mf17YFJ7WyaWKI_V-2clpgXU7--BAOKV/view',
    vin: 'SUCE2ASA4N1004725',
  },
  {
    name: 'VOZIK 8 (dlouhý na převozy aut)',
    type: 'TRAILER' as VehicleType,
    registrationNumber: '1UI 0311',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-05-29'),
    insuranceUntil: new Date('2026-11-01'),
    owner: 'SP',
    vin: 'SZRBR2000M0010904',
  },

  // FIREMNÍ AUTA
  {
    name: 'AUTO 1 (Octavia kombi zlaťák)',
    type: 'CAR' as VehicleType,
    registrationNumber: '9B9 9071',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-02-06'),
    insuranceUntil: new Date('2026-11-01'),
    responsiblePerson: 'Soník',
    tiresInfo: '195/65 R15 (Celoroční)',
    repairNotes: 'nejdou sundat okna přední Karel šprajc, zadní dveře nejdou otevřít',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1Hl2FYZ_2CPSVlrP3dK5iMx5L2zyE4mrM/view',
    vin: 'TMBGP21U112464251',
  },
  {
    name: 'AUTO 2 (Octavia kombi Karel)',
    type: 'CAR' as VehicleType,
    registrationNumber: '7T8 8363',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2028-06-25'),
    insuranceUntil: new Date('2026-11-01'),
    highwayPassUntil: new Date('2027-01-30'),
    responsiblePerson: 'Karel',
    tiresInfo: '195/65 R15 (Celoroční)',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1iDCrt657hsyLXuXgfjjeniFv6Hop6bsr/view',
    vin: 'TMBKS21U138675877',
  },
  {
    name: 'AUTO 3 (Octavia kombi Pavel)',
    type: 'CAR' as VehicleType,
    registrationNumber: '5T2 5481',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-08-23'),
    insuranceUntil: new Date('2025-09-19'),
    responsiblePerson: 'Pavel',
    tiresInfo: '195/65 R15 (Celoroční)',
    repairNotes: 'zalomený zámek u řidiče, nefunkční stěrače, nový olej a filtry, abs, nejdou otevřít zadní dveře levá',
    owner: 'QX',
    vtpUrl: 'https://drive.google.com/file/d/1-vLvnHVaT12Qw5FnBa6Mgf4rQLGjDIuS/view',
    vin: 'TMBHP21U738685230',
  },
  {
    name: 'AUTO 4 (Seat)',
    type: 'CAR' as VehicleType,
    registrationNumber: '1AD 8081',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2026-09-11'),
    insuranceUntil: new Date('2025-09-19'),
    responsiblePerson: 'Soník',
    tiresInfo: '195/65 R15 (Celoroční)',
    owner: 'QX',
    vtpUrl: 'https://drive.google.com/file/d/19uphAfYYtM0mNkasHPwob4a3v8Cy5jsJ/view',
    vin: 'VSSZZZ6LZ7R052897',
  },
  {
    name: 'AUTO 5 (MODRÁ Renault Master Dodávka)',
    type: 'VAN' as VehicleType,
    registrationNumber: '2T8 7227',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2028-05-06'),
    insuranceUntil: new Date('2026-11-01'),
    highwayPassUntil: new Date('2027-05-06'),
    responsiblePerson: 'Karel',
    tiresInfo: '195/65 R16 (Celoroční)',
    repairNotes: 'klíč, nádržka na ostřikovače, koupit disk rezervu',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1wGgVq74oKWFmVk_eeTPAyUZyam8Q5kG5/view',
    vin: 'VF1FDAKD532131897',
  },
  {
    name: 'AUTO 6 (BÍLÁ Renault Trafic)',
    type: 'VAN' as VehicleType,
    registrationNumber: '1TS 6933',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-11-20'),
    insuranceUntil: new Date('2026-09-05'),
    highwayPassUntil: new Date('2026-09-14'),
    responsiblePerson: 'Jiřík',
    tiresInfo: '205/65 R16 (Celoroční)',
    repairNotes: 'doplnit klima - jaro, nefungují větráky',
    owner: 'QX',
    vtpUrl: 'https://drive.google.com/file/d/1SrEn_0IQSjIvXRUgbNWPHpW_0UYPQoHw/view',
    vin: 'VF1FLBHB6AV361906',
  },
  {
    name: 'AUTO 7 (H1 Dodávka)',
    type: 'VAN' as VehicleType,
    registrationNumber: '5T8 0927',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-03-12'),
    insuranceUntil: new Date('2026-11-01'),
    highwayPassUntil: new Date('2027-01-20'),
    tiresInfo: '205/70 R15 (Celoroční)',
    repairNotes: 'Po 500km - dojet na kontrolu motoru',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1GJuKLyeS9tVueaXd74WKPVYaRANmZT1/view',
    vin: 'NLJWVH7JP7Z081693',
  },
  {
    name: 'AUTO 8 (Ford Focus)',
    type: 'CAR' as VehicleType,
    registrationNumber: '8B2 2383',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-07-29'),
    insuranceUntil: new Date('2026-11-01'),
    tiresInfo: 'Celoroční',
    vin: 'WF05XXWPD56R65799',
  },
  {
    name: 'AUTO 9 (Octavia kombi černá Mirek)',
    type: 'CAR' as VehicleType,
    registrationNumber: '1TK 2207',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-07-15'),
    responsiblePerson: 'Mirek',
    tiresInfo: 'Celoroční',
    vin: 'TMBGE61Z262216784',
  },
  {
    name: 'AUTO 10 (VW Tiguan Allspace Vlaďka)',
    type: 'CAR' as VehicleType,
    registrationNumber: '7AK 6097',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-02-18'),
    highwayPassUntil: new Date('2027-02-26'),
    responsiblePerson: 'Vlaďka',
    tiresInfo: '235/55 R18V (Zimní)',
    repairNotes: 'kotouče',
    owner: 'SP (Generali)',
    vtpUrl: 'https://drive.google.com/file/d/1zI719D7tGEe256VajF7pgmoj2uEHsqR7/view',
    vin: 'WVGZZZ5NZKM055335',
  },
  {
    name: 'AUTO 11 (VW Arteon Marek)',
    type: 'CAR' as VehicleType,
    registrationNumber: '1TU 2677',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-01-29'),
    highwayPassUntil: new Date('2027-01-31'),
    responsiblePerson: 'Marek',
    tiresInfo: '245/45 R18 m+s (Zimní)',
    repairNotes: 'předělat elektriku na počítači',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1quIHBiqId6fgeNudqJnK6pmibP9koeO5/view',
    vin: 'WVWZZZ3HZLE008860',
  },
  {
    name: 'AUTO 12 (VW Passat Silva)',
    type: 'CAR' as VehicleType,
    registrationNumber: '2TF 5672',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2028-06-12'),
    responsiblePerson: 'Silva',
    tiresInfo: 'Zimní',
    owner: 'Silva',
  },
  {
    name: 'AUTO 12 (Fabie červená)',
    type: 'CAR' as VehicleType,
    registrationNumber: '5T4 9632',
    status: 'AVAILABLE' as VehicleStatus,
    technicalInspectionUntil: new Date('2027-11-07'),
    repairNotes: 'klíček dodělat',
  },

  // OSTATNÍ / MIMO FIRMU
  {
    name: 'Škoda Superb (Pedro)',
    type: 'CAR' as VehicleType,
    registrationNumber: '4T8 7213',
    status: 'OUT_OF_SERVICE' as VehicleStatus,
    technicalInspectionUntil: new Date('2025-11-22'),
    responsiblePerson: 'Pedro',
    vin: 'TMBDC23U879017136',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1ob3K0PIHkrZ9yXlMnsH7QI2m0BmxA-zk/view',
  },
  {
    name: 'Skútr Maxon 1 (Pedro)',
    type: 'OTHER' as VehicleType,
    registrationNumber: '5T4 960',
    status: 'OUT_OF_SERVICE' as VehicleStatus,
    technicalInspectionUntil: new Date('2026-03-28'),
    responsiblePerson: 'Pedro',
    vin: 'LLPTCJA17AA170391',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1VZQLkkQ5EudMPn2FkSbJDr0YdEt_cOiT/view',
  },
  {
    name: 'Skútr Maxon 2 (Pedro)',
    type: 'OTHER' as VehicleType,
    registrationNumber: '4T4 497',
    status: 'OUT_OF_SERVICE' as VehicleStatus,
    technicalInspectionUntil: new Date('2025-07-20'),
    responsiblePerson: 'Pedro',
    vin: 'LLPTCJA17D1D00362',
    owner: 'SP',
    vtpUrl: 'https://drive.google.com/file/d/1ivlsb-y2nhgwxi5JqI6v0IVsuqqmUkRK/view',
  },
  {
    name: 'AUTO Tiguan starý (Dagmar)',
    type: 'CAR' as VehicleType,
    registrationNumber: '6T1 4844',
    status: 'OUT_OF_SERVICE' as VehicleStatus,
    technicalInspectionUntil: new Date('2026-12-10'),
    highwayPassUntil: new Date('2027-01-06'),
    responsiblePerson: 'Dagmar Konečná',
    tiresInfo: '216/65 R16',
    vin: 'WVGZZZ5NZAW013019',
    owner: 'Marek Konečný',
    vtpUrl: 'https://drive.google.com/file/d/1GNZCj0eRtiFghVOrZ84LUuQonibfR2TR/view',
  },
];

export async function seedVehiclesFromExcel() {
  let count = 0;
  for (const item of vehiclesData) {
    const existing = await prisma.vehicle.findFirst({
      where: {
        OR: [
          ...(item.registrationNumber ? [{ registrationNumber: item.registrationNumber }] : []),
          { name: item.name },
        ],
      },
    });

    if (!existing) {
      await prisma.vehicle.create({ data: item });
      count++;
    } else {
      await prisma.vehicle.update({
        where: { id: existing.id },
        data: {
          name: item.name,
          type: item.type,
          technicalInspectionUntil: item.technicalInspectionUntil ?? existing.technicalInspectionUntil,
          insuranceUntil: item.insuranceUntil ?? existing.insuranceUntil,
          highwayPassUntil: item.highwayPassUntil ?? existing.highwayPassUntil,
          responsiblePerson: item.responsiblePerson ?? existing.responsiblePerson,
          tiresInfo: item.tiresInfo ?? existing.tiresInfo,
          repairNotes: item.repairNotes ?? existing.repairNotes,
          owner: item.owner ?? existing.owner,
          vtpUrl: item.vtpUrl ?? existing.vtpUrl,
          vin: item.vin ?? existing.vin,
        },
      });
    }
  }
  return count;
}

if (require.main === module) {
  seedVehiclesFromExcel()
    .then((c) => {
      console.log(`Successfully seeded ${c} vehicles/trailers from Google Sheet!`);
      process.exit(0);
    })
    .catch((err) => {
      console.error('Seed error:', err);
      process.exit(1);
    });
}
