import { writeFileSync } from 'node:fs';
const groups = [
  ['START','Začínáme','P0','ALL','/profile','Aktivovat účet a obnovit heslo|Přihlásit se a ověřit organizaci|Přepnout aktivní roli a poznat dostupné moduly|Najít svoji agendu na nástěnce|Upravit profil|Přečíst oznámení a otevřít související úkol'],
  ['MAP','Mapa a reklamní nosiče','P0','ADMIN MANAGER SALES TECHNICIAN VIEWER','/map','Najít nosič podle mapy a filtrů|Rozlišit nosič a reklamní plochu|Přečíst detail plochy a klienta|Upravit údaje a GPS nosiče|Přidat nosič a ověřit jeho typ|Otevřít galerii a ověřit klientskou viditelnost'],
  ['PHOTO','Focení a fotodokumentace','P0','ADMIN MANAGER SALES TECHNICIAN WORKER','/mobile-photos','Vyfotit existující nosič s GPS|Vybrat správnou stranu a účel fotografie|Vyřešit návrh nesprávného přiřazení plochy|Nahlásit poškození nosiče fotografií|Rozlišit uloženou fotografii a chybu vedlejší akce|Postupovat při zamítnuté GPS nebo neúspěšném uploadu'],
  ['NAV','Navigační zakázky','P0','ADMIN MANAGER SALES TECHNICIAN WORKER','/navigation','Připravit navigační nabídku pro více provozoven|Doplnit body a terénní fotografie|Nechat klienta vybrat lokality bez objednání realizace|Nacenit vybranou navigační trasu|Převést schválenou cenovou nabídku do realizace|Připravit smlouvu a grafické podklady|Naplánovat instalaci a přiřadit pracovníky|Dokončit montáž s fotografií a kontrolou kvality|Sestavit a sdílet klientskou fotodokumentaci|Řízeně změnit přijatou navigační zakázku|Připravit fakturační období a fakturu|Provést průzkum lokalit k navigaci'],
  ['OFFER','Nabídky a obchod','P0','ADMIN MANAGER SALES','/offers','Vytvořit standardní nabídku klientovi|Vybrat typ nabídky a šablonu|Sestavit výběr ploch a termín|Zkontrolovat cenu a připravenost nabídky|Odeslat nebo sdílet klientskou nabídku|Zpracovat dotaz a požadavek na úpravu|Rozlišit přijetí odmítnutí a expiraci|Připravit nabídku výstavní sítě'],
  ['OCC','Obsazenost a rezervace','P0','ADMIN MANAGER SALES','/occupancy','Ověřit dostupnost plochy v termínu|Založit rezervaci a odlišit ji od jednání|Vyřešit překryv termínů|Změnit nebo ukončit rezervaci|Zkontrolovat obsazenost po přijetí nabídky'],
  ['CRM','Klienti a komunikace','P1','ADMIN MANAGER SALES','/clients','Založit a dohledat klienta|Přidat kontakt a pobočku|Najít nabídky a zakázky v kartě klienta|Zapsat komunikaci a navazující CRM úkol|Najít smlouvu a klientský dokument|Zkontrolovat a sloučit duplicitu klienta'],
  ['REAL','Realizace zakázek','P0','ADMIN MANAGER SALES ACCOUNTANT','/realization','Zjistit další krok po potvrzení objednávky|Vyřešit chybějící podklady a blokaci|Předat položku do výroby|Zkontrolovat instalaci a fotodokumentaci|Předat hotovou realizaci k fakturaci|Zpracovat změnový požadavek'],
  ['WORK','Práce a zaměstnanci','P1','ADMIN MANAGER SALES TECHNICIAN WORKER ACCOUNTANT','/my-tasks','Převzít vlastní úkol|Najít pracovní příkaz a trasu výjezdu|Odevzdat dokončenou práci|Vykázat práci a výdaj|Odevzdat vlastní vyúčtování|Schválit výkaz pracovníka|Požádat o volno a ověřit kolizi|Najít kontakt a použít týmový chat|Přidat pracovníka a nastavit sazby'],
  ['FIN','Finance a fakturace','P1','ADMIN MANAGER ACCOUNTANT','/settlements','Rozlišit klientskou fakturu a fakturu pracovníka|Zkontrolovat a schválit vyúčtování|Uzamknout vyúčtování a evidovat platbu|Vytvořit klientskou fakturu v kontextu zakázky|Najít fakturu a její stav v kartě klienta|Zkontrolovat náklady a finanční přehled'],
  ['AI','AI nástroje','P1','ADMIN MANAGER SALES','/commercial','Zkontrolovat návrh v AI Inboxu|Potvrdit nebo odmítnout navrženou akci|Vyhodnotit signál obchodního radaru|Použít AI obchodní centrum a dohledat zdroj|Vyhodnotit AI upozornění na obsazenost|Nadiktovat rychlý interní úkol|Ověřit návrh AI rozpoznání fotografie|Rozpoznat neověřenou nebo nedostupnou AI odpověď'],
  ['SURVEY','Field Survey','P1','ADMIN MANAGER SALES TECHNICIAN WORKER','/field-survey','Založit samostatný terénní průzkum|Zaznamenat bod s GPS a fotografií|Doplnit parcelu vlastníka a kontakt|Posoudit AI analýzu místa|Exportovat průzkum do KML GeoJSON nebo XLSX'],
  ['ADMIN','Administrace a nastavení','P2','ADMIN','/settings','Pozvat uživatele do organizace|Nastavit role a ověřit přístup|Nastavit firemní profil a fakturační údaje|Připojit integraci a ověřit její stav|Nastavit firemní odesílání e-mailů|Připravit import a zkontrolovat dry-run|Spravovat typy nosičů a produkty|Dokončit onboarding organizace|Spravovat organizace jako platformní administrátor'],
  ['PLAN','Plánovač a kalendář','P1','ADMIN MANAGER SALES TECHNICIAN WORKER ACCOUNTANT','/planner','Naplánovat osobní pracovní blok|Připojit kalendář a zvolit synchronizaci|Vyřešit souběh práce a absence|Najít termíny vyžadující pozornost'],
  ['STOCK','Sklad a nákupy','P1','ADMIN MANAGER TECHNICIAN WORKER','/warehouse','Najít materiál přes QR|Zapsat příjem a výdej materiálu|Zkontrolovat nízkou zásobu|Připravit nákupní požadavek|Použít a ověřit AI návrh skladových položek'],
  ['CAR','Vozidla a provoz','P1','ADMIN MANAGER SALES TECHNICIAN WORKER','/vehicles','Rezervovat vozidlo|Zapsat tankování a ověřit účtenku|Zaznamenat servis a stav vozidla'],
  ['NET','Výstavní sítě a inventář','P2','ADMIN MANAGER SALES','/projects/city-gallery','Založit a sledovat projekt výstavní sítě|Dohledat městský inventář|Orientovat se v omezeních B2B Network'],
  ['ELECT','Volební demontáže','P2','ADMIN MANAGER TECHNICIAN WORKER','/election-removal','Importovat kampaň a ověřit body|Naplánovat trasu demontáží|Dokončit bod v mobilu|Předat demontovaný materiál a uzavřít trasu'],
] as const;
const lessons = groups.flatMap(([prefix,category,priority,roles,route,titles])=>titles.split('|').map((title,i)=>({id:`${prefix}-${String(i+1).padStart(2,'0')}`,category,title,priority,roles:roles.split(' '),entryRoute:route,status:'PLANNED',estimatedMinutes:3,verification:'UNVERIFIED',verifiedAt:null,media:[],prerequisites:'Aktivní organizace, oprávnění příslušné akce a zapnutý modul; upřesnit při validaci.',note:'Kategorie určuje výchozí publikum, jednotlivá akce může vyžadovat užší oprávnění. EntryRoute je vstup do agendy, ne nutně vlastní obrazovka kroku.'})));
const pilotIds=['START-03','PHOTO-01','NAV-03','NAV-05','SURVEY-02'];
for(const lesson of lessons) if(pilotIds.includes(lesson.id)){lesson.status='MEDIA_PENDING';lesson.verification='CODE_REVIEWED; BROWSER_UNVERIFIED';}
writeFileSync('reports/academy-2026-10-08/lessons.json',JSON.stringify(lessons,null,2));
const intro = `# Struktura a katalog Akademie\n\n${lessons.length} navržených lekcí v ${groups.length} kategoriích. Jde o úplný výchozí backlog objevených domén, nikoli tvrzení o vyčerpání všech variant formulářů. Před publikací se každý řádek ověří ve své konkrétní roli a modulu. Odhad 3 min je výchozí návrh; u videí cílit 1–3 min a větší činnost rozdělit.\n\n## Navigace modulu\n\n/academy: moje povinné zaškolení, pokračování v lekci, hledání podle úkolu, kategorie. /academy/lessons/[slug]: kroky, médium, časté chyby, ověření, dokončení, nahlášení problému. /academy/paths/[id]: povinné a volitelné lekce. /academy/manage: přiřazení a přehled postupu; /academy/manage/content: redakce a publikace. Všechny tyto adresy jsou **navržené**, v současné aplikaci neexistují.\n\n## Stav a verifikace\n\nPLANNED = téma v backlogu. VERIFIED = obsah ověřen bezpečným browser průchodem a schválen odborným vlastníkem. MEDIA_PENDING = text/scénář připraven, chybí média; samotný tento stav neprokazuje runtime ověření. READY = ověřený obsah, média, přístupnost a odkazy, čeká na publikaci. PUBLISHED = zveřejněná neměnná revize. OUTDATED = změna UI/policy nebo potvrzený problém vyžaduje revizi. Archivace je samostatný archivedAt, nikoli ztráta historie.\n\nBěžná cesta: PLANNED → VERIFIED → MEDIA_PENDING (jsou-li potřeba média) → READY → PUBLISHED → OUTDATED → nová revize. Pilotní koncept může být MEDIA_PENDING již před browser verifikací; READY musí vždy vyžadovat verifiedAt i schválení. Pět pilotů má runtime UNVERIFIED a verifiedAt=null; žádná lekce se nyní nevydává za hotovou.\n\n## Personalizované cesty\n\n- WORKER: START-02/03 → WORK-01/02 → PHOTO-01/02 → WORK-03/04/05. Jen vlastní práce a skutečně dostupné moduly.\n- TECHNICIAN: pracovník + NAV-08/12 → SURVEY-02 → STOCK-01/02.\n- SALES: START-03 → CRM-01/02 → OFFER-01/03/04/05 → NAV-01/03/04 → OCC-01/03. Interní přijetí nabídky neudělovat.\n- MANAGER: obchod + NAV-05 → REAL-01/02/05 → WORK-06 → AI-01/02.\n- ACCOUNTANT: START-03 → FIN-01/02/03/04/05 → WORK-06 → REAL-05, pouze povolená data; účetní nemusí mít samostatný přístup do klientského adresáře.\n- ADMIN: START-03 → ADMIN-01/02/03/04/05/06, pak role odpovídající pracovní náplni. Platformní ADMIN-09 jen pro SUPER_ADMIN.\n- VIEWER: START-02/03/04 → MAP-01/02/03; bez lekcí navádějících k mutacím.\n\nPřiřazená povinná lekce se při odebrání modulu/role označí BLOCKED_BY_ACCESS; nezapočítat ji jako nesplněný osobní výkon. Změna aktivní role může změnit katalog, ale historii dokončení nesmazat. Správce cesty může přidat povinnost pouze k oprávněnému publiku.\n\n## Katalog\n\nRole níže jsou výchozí publikum kategorie, **ne hotová autorizační matice akcí**. Například editaci nosiče nesmí získat VIEWER; schvalování výkazů je užší než vlastní evidence. Před READY je nutné lesson.requiredCapabilities odvodit z konkrétního serverového guardu. Ve strojovém katalogu je pro každou lekci i vstupní route, předpoklady, ověření a prázdná média.\n\n`;
let md=intro;
for(const [,category,priority,roles,route] of groups){md+=`### ${category}\n\nPriorita ${priority}; výchozí publikum ${roles}; vstup \`${route}\`.\n\n| ID | Konkrétní pracovní úkol | Stav |\n|---|---|---|\n`;md+=lessons.filter(l=>l.category===category).map(l=>`| ${l.id} | ${l.title} | ${l.status} |`).join('\n')+'\n\n';}
writeFileSync('reports/academy-2026-10-08/03-katalog-lekci.md',md);
console.log(`${lessons.length} lessons, ${groups.length} categories, ${pilotIds.length} pilots.`);
